### ISSUE TITLE
Testing comments

### ISSUE THREAD

**Issue by mattdsteele** [mattdsteele/arnoldc.js#5]
I wonder how great this will be? Probably pretty awesome.

**Comment by mattdsteele** [comment]
Foo bar foo bar great!

**Comment by mattdsteele** [comment]
Another comment awesome!

**Comment by javazquez** [comment]
These are the best!

**Comment by mattdsteele** [comment]
@javazquez Try submitting another comment :)

**Comment by javazquez** [comment]
Will do! Hope this helps

**Comment by javazquez** [comment]
It’s a hot mess

**Comment by javazquez** [comment]
I don’t want to be ANALIZED!!!!

**Comment by javazquez** [comment]
Does sentiment take caps into account?

**Comment by mattdsteele** [comment]
Uh oh it's only looking at the initial Issue post, not each subsequent comment. Guess I have some debugging to do...

IIRC it's only looking at the polarity of individual words, so probably not. https://www.npmjs.com/package/natural#sentiment-analysis

**Comment by mattdsteele** [comment]
Good enough for now. This is some extremely advanced sentiment analysis. Really top of the line. 🙄
